spring:
  datasource:
    # 메모리 모드 H2 설정: 테스트가 끝나면 데이터가 자동으로 날아갑니다.
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 테스트마다 테이블을 새로 만들고 삭제합니다.
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # H2에서 MySQL 문법을 어느 정도 이해하도록 설정합니다.
        dialect: org.hibernate.dialect.H2Dialect